function [J grad] = nnCostFunction(nn_params, input_layer_size,hidden_layer_size, hidden_layer_size_2, num_labels,X, y, lambda)
m = size(X, 1);
Theta1 = reshape(nn_params(1:hidden_layer_size * (input_layer_size + 1)),hidden_layer_size, (input_layer_size + 1));
Theta2 = reshape(nn_params(6901:127300),hidden_layer_size_2, (hidden_layer_size + 1));
Theta3 = reshape(nn_params(127301:end),num_labels, (hidden_layer_size_2 + 1));       
J = 0;
Theta1_grad = zeros(size(Theta1));
Theta2_grad = zeros(size(Theta2));
Theta3_grad = zeros(size(Theta3));
X = [ones(m,1) X];
Y = zeros(m,num_labels);
for i=1:m
	j = y(i);
	Y(i,j) = 1;
end;
a1 = sigmoid(X*Theta1');
a1 = [ones(m,1) a1];
a2 = sigmoid(a1*Theta2');
a2 = [ones(size(a2,1),1) a2];
h = exp(a2*Theta3')./sum(exp(a2*Theta3'),2);
S = sum(sum(-(Y.*log(h)), 2));
j = S./m;
t = Theta1.*Theta1;
u = Theta2.*Theta2;
v = Theta3.*Theta3;
sum1 = sum(sum((t),2)) - sum(t(:,1));
sum2 = sum(sum((u),2)) - sum(u(:,1));
sum3 = sum(sum((v),2)) - sum(v(:,1));
J = j + ((lambda/(2*m))*(sum1+sum2+sum3));
Delta1 = zeros(hidden_layer_size,size(X,2));
Delta2 = zeros(hidden_layer_size_2,hidden_layer_size+1);
Delta3 = zeros(num_labels,hidden_layer_size_2+1);
for t = 1:m
	a1 = X(t,:);
	z2 = a1*Theta1';
	a2 = sigmoid(z2);
	a2 = [1 a2];
	z3 = (a2*Theta2');
	a3 = sigmoid(z3);
	a3 = [1 a3];
	z4 = a3*Theta3';
	a4 = exp(z4)./sum(exp(z4),2);
	delta4 = a4 - Y(t,:);
	delta3 = delta4*Theta3(:,(2:end)).*sigmoidGradient(z3);
	delta2 = delta3*Theta2(:,(2:end)).*sigmoidGradient(z2);
	Delta1 = Delta1 + delta2'*a1;
	Delta2 = Delta2 + delta3'*a2;
	Delta3 = Delta3 + delta4'*a3;
	end
Theta1_grad = Delta1./m + (lambda/m).*Theta1;
Theta2_grad = Delta2./m + (lambda/m).*Theta2;
Theta3_grad = Delta3./m + (lambda/m).*Theta3;
Theta1_grad(:,1) = Theta1_grad(:,1) - (lambda/m).*Theta1(:,1);
Theta2_grad(:,1) = Theta2_grad(:,1) - (lambda/m).*Theta2(:,1);
Theta3_grad(:,1) = Theta3_grad(:,1) - (lambda/m).*Theta3(:,1);
grad = [Theta1_grad(:) ; Theta2_grad(:) ; Theta3_grad(:)];
end
